### ISSUE TITLE
Exitcode None

### ISSUE THREAD

**Issue by HackerMD** [uzh/gc3pie#507]
The `execution.exitcode` attribute of some tasks is `None` on a SLURM cluster. It occurs for about 1% of submitted jobs. Any task can be affected, not only the ones active during the latest `engine.progress()` iteration.

The `execution.returncode` as well as `execution.signal` attributes also have value `None`.

These tasks further miss the following attributes, compared to tasks that have an integer return status:
* `execution.slurm_completion_time `
* `execution.slurm_max_used_ram`
* `execution.slurm_start_time`
* `execution.slurm_submission_time`
* `execution.max_used_memory`
* `execution.duration`
* `execution.cores`

Of note, `execution.state` is `TERMINATING` for both types of tasks, while `execution._state` is `TERMINATED`.

**Comment by HackerMD** [comment]
`sacct -j <job_id>` for an example job, where `job.execution.exitcode = None` and `job.execution.lrms_jobid = 486862`, shows the following:

```
$ sacct -j 486862
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- -------- 
486862       imextract+      cloud      cloud          1  COMPLETED      0:0 
486862.batch      batch                 cloud          1  COMPLETED      0:0 
```

**Comment by riccardomurri** [comment]
I have a theory on how this could happen.  If *all* of the following
conditions happen in a SLURM cluster, then GC3Pie would only set the
state of a task to `TERMINATED` but *not* reap the exit code or any of
the resource usage metrics:

1. The SLURM job has recently terminated, so `squeue -j $JOBID` exits
   with code 0, but produces no output.  GC3Pie (correctly) reacts to
   this by setting the task's state to TERMINATED.

2. For whatever reason, the `sacct -j $JOBID` command does *not* run
   correctly and exits with a non-zero code. GC3Pie should try to run
   a "secondary" accounting command, which is not defined on SLURM (it
   only exists on PBSPro and LSF) and then (incorrectly) ignores the
   error.

Condition 2. could be triggered by the fact that SLURM has to write
many accounting records to the database, so `sacct` can be delayed and
eventually time out if many jobs are finishing at about the same time.

The unlikeliness of both conditions could explain why the incidence of
this bug seems so low even for a large number of jobs.

Unfortunately, GC3Pie will silently ignore condition 2. so there is no
way we can detect this from the logs or other traces.

There is little doubt, however, that the code in `backends/batch.py`
and `backends/slurm.py` is incorrect and should be fixed.

**Comment by riccardomurri** [comment]
I think this is fixed in the "develop" branch (commit 1e06a83). Can you please test it?

You can find instructions on how to use `pip install` with GitHub branches here: http://stackoverflow.com/questions/20101834/pip-install-from-github-repo-branch

**Comment by HackerMD** [comment]
Great!

I’ll give it a test tmw. I’m currently re-running the jterator pipeline. It looks good so far, it seems that the additional Matlab startup options do the trick.

Thanks a lot Ricardo!

**Comment by HackerMD** [comment]
I've tested it and it seems to be fixed. Thank you very much!

**Comment by riccardomurri** [comment]
Thank you for testing so thouroughly!

I'd like to keep the issue open but marked "fix available" until the fix has been merged into "master"
